### ISSUE TITLE
Some Twitter spaces do not download

### ISSUE THREAD

**Issue by soraphoenix** [89z/mech#12] opened 2022-01-20 21:33 UTC
After successfully downloading a space, the ones I tried after are rejected or not found.

Here's one example:
```
c:\> twitter -s 1ypKdEMkYOpGW
POST https://api.twitter.com/1.1/guest/activate.json
GET https://twitter.com/i/api/graphql/Uv5R_-Chxbn1FEkyUkSW2w/AudioSpaceById?variables=%7B%22id%22%3A%221ypKdEMkYOpGW%22%2C%22isMetatagsQuery%22%3Afalse%2C%22withBirdwatchPivots%22%3Afalse%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%2C%22withReplays%22%3Afalse%2C%22withScheduledSpaces%22%3Afalse%2C%22withSuperFollowsTweetFields%22%3Afalse%2C%22withSuperFollowsUserFields%22%3Afalse%7D
GET https://twitter.com/i/api/1.1/live_video_stream/status/28_1483553630607200258
GET https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/BxqVn5iddRLqdeW2erAtuUCIrkZ8rm4TuPAMD7DPdyyy_TLtebOifEyesISRcLwGnTaXkOWnKmFOW3ywNip49g/non_transcode/us-east-1/periscope-replay-direct-prod-us-east-1-public/audio-space/playlist_16804176186266944010.m3u8?type=replay
panic: open TechRally 🇰🇷🇺🇸,Stephanieᵍᵐ,Mike Chen🌱-Self Taught & Coding Bootcamp to PayPal/Google/Amazo    n Ask Questions!.aac: The system cannot find the path specified.

goroutine 1 [running]:
main.main()
        D:/Git/mech/cmd/twitter/main.go:29 +0x1f7
```

I'm able to pull info on them though:
```
c:\> twitter -i -s 1ypKdEMkYOpGW
POST https://api.twitter.com/1.1/guest/activate.json
GET https://twitter.com/i/api/graphql/Uv5R_-Chxbn1FEkyUkSW2w/AudioSpaceById?variables=%7B%22id%22%3A%221ypKdEMkYOpGW%22%2C%22isMetatagsQuery%22%3Afalse%2C%22withBirdwatchPivots%22%3Afalse%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%2C%22withReplays%22%3Afalse%2C%22withScheduledSpaces%22%3Afalse%2C%22withSuperFollowsTweetFields%22%3Afalse%2C%22withSuperFollowsUserFields%22%3Afalse%7D
GET https://twitter.com/i/api/1.1/live_video_stream/status/28_1483553630607200258
Admins: TechRally 🇰🇷🇺🇸,Stephanieᵍᵐ,Mike Chen🌱
Title: Self Taught & Coding Bootcamp to PayPal/Google/Amazon Ask Questions!
Duration: 2h50m38.113s
Location: https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/BxqVn5iddRLqdeW2erAtuUCIrkZ8rm4TuPAMD7DPdyyy_TLtebOifEyesISRcLwGnTaXkOWnKmFOW3ywNip49g/non_transcode/us-east-1/periscope-replay-direct-prod-us-east-1-public/audio-space/playlist_16804176186266944010.m3u8?type=replay
```

**Comment by 89z** [comment] 2022-01-20 22:14
Hello. The issue is caused by the Title:

~~~
Title: Self Taught & Coding Bootcamp to PayPal/Google/Amazon Ask Questions!
~~~

File name cannot have `/` character. I will try to fix this.

https://github.com/89z/mech/blob/e53af43e0e797a90a105191b71262ff221967e1b/cmd/twitter/space.go#L34

**Comment by 89z** [comment] 2022-01-20 22:19
This should be fixed now:

https://github.com/89z/mech/releases/tag/v1.45.3

**Closed by 89z** 2022-01-20 22:19 UTC

**Comment by soraphoenix** [comment] 2022-01-21 02:49
Thanks, that was a quick turnaround. I had a feeling the title was causing issues.

**Comment by 89z** [comment] 2022-02-24 02:02
https://github.com/ytdl-org/youtube-dl/issues/29145
